from alpine:latest
LABEL version="3.15.0" maintainer="maintainer" os="distro"
ENV CONTAINER_USER="sara"
RUN mkdir $CONTAINER_USER
cmd CONTAINER_USER > "hello-alpine, I’m sara and this is a container from my first image"


