FROM alpine:latest
LABEL version="3.15.0" maintainer="maintainer" os="distro"
ENV CONTAINER_USER="saral1011"
CMD echo "hello-alpine, I’m $CONTAINER_USER  and this is a container from my first image"

